name: Interface Tests

on:
  pull_request:
    branches:
      - main  

jobs:
  test:
    runs-on: ubuntu-latest  

    steps:
      - name: Checkout do código
        uses: actions/checkout@v4 

      - name: Configurar ambiente Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.13.1"

      - name: Instalar dependências
        run: |
          pip install -r requirements.txt
          sudo apt-get update
          sudo apt-get install -y chromium-chromedriver 

      - name: Iniciar um servidor local para o front-end
        run: |
          python -m http.server 8000 & 

      - name: Rodar testes Selenium
        run: python main.py  
